---
title: "Report2"
format: 
  pdf:
    include-in-header: SOE-NEFMC-master/SOE-NEFMC-master/latex/header1.tex
    text: |
      \usepackage{fancyhdr}
      \pagestyle{fancy}
      \fancyhead[C]{Header text}
      \fancyfoot[L]{Footer text}
editor: visual
execute:
  echo: false
---

```{r setup, message = FALSE, warnings = FALSE}
devtools::install_github("https://github.com/MandyKarnauskas-NOAA/plotTimeSeries.git")

library(plotTimeSeries)
library(spam)
```

# Introduction

## About This Report

This report is for ....

## Report structure

This is the structure of the report....

## Cool indicators

Wow, look at that aragonite saturation state...

```{r, message = FALSE, warnings = FALSE}
load("indicator_objects/OA.RData")
plotIndicatorTimeSeries(inddata, trendAnalysis = F)
```

Here is the gini index showing equality in distribution of revenues....

```{r}
load("indicator_objects/gini.RData")
plotIndicatorTimeSeries(inddata, coltoplot = 1:2, plotrownum = 2, trendAnalysis = F, sublabel = T)
```

